server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_app_db_test
    username: postgres
    password: 2002
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
        enable_lazy_load_no_trans: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  access:
    key: heruighurighviey84y57yuvhrjhvrhtvrhtvhjr8u4v8njvertvn8ut8veu834uvndjkwe
    expiration-time: 7200000000
  refresh:
    key: evjrkhertvuheruth84y574y587yvbrhvjrtvhrjthv3u4895vuntervnjtkejrht89545y
    expiration-time: 604800000


app:
  running: test
  admin:
    firstName: "MuhammadQodir"
    phoneNumber: "+998931668648"
    password: "123"